<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authService } from '@/features/auth/services/authService'
import PasswordInput from '@/components/common/PasswordInput.vue'
const name=ref(''),email=ref(''),password=ref(''),confirmPassword=ref(''),error=ref(''); const router=useRouter()
const register=async()=>{if(password.value!==confirmPassword.value){error.value='Passwords do not match.';return}try{await authService.register({name:name.value,email:email.value,password:password.value});await router.push('/login')}catch(err){error.value=err.response?.data?.message||'Unable to create the account.'}}
</script>
<template><main class="join-experience"><section class="join-story"><div><span class="join-mark"><i class="bi bi-person-plus-fill"></i></span><span>EMPLOYEE MANAGEMENT</span><h1>Set up your<br>workspace access.</h1><p>Create your account and start managing people with clarity.</p></div></section><section class="join-form-side"><div class="join-form-wrap"><RouterLink to="/login" class="join-mobile-brand"><i class="bi bi-people-fill"></i> Employee Management</RouterLink><div class="join-intro"><span>GET STARTED</span><h2>Create account</h2><p>Use your work details to join the workspace.</p></div><form @submit.prevent="register" class="join-form"><label>Full name<input v-model="name" class="form-control" placeholder="Your full name" required></label><label>Work email<input v-model="email" type="email" class="form-control" placeholder="you@company.com" required></label><div class="join-fields"><label>Password<PasswordInput id="password" v-model="password" placeholder="Create password" autocomplete-mode="new-password" required /></label><label>Confirm password<PasswordInput id="confirm-password" v-model="confirmPassword" placeholder="Confirm password" autocomplete-mode="new-password" required /></label></div><div v-if="error" class="alert alert-danger mb-0">{{ error }}</div><button class="btn btn-primary">Create account <i class="bi bi-arrow-right"></i></button></form><p>Already have access? <RouterLink to="/login">Sign in</RouterLink></p></div></section></main></template>
<style scoped>
.join-experience{display:grid;min-height:100vh;grid-template-columns:.82fr 1.18fr;background:#fff}.join-story{display:flex;align-items:end;padding:clamp(40px,7vw,100px);background:#dfe5f3;color:#26375f}.join-story>div{max-width:360px}.join-mark{display:inline-flex;width:46px;height:46px;align-items:center;justify-content:center;margin-bottom:28px;border-radius:8px;background:#fff;color:var(--color-primary);box-shadow:0 8px 20px rgba(35,51,89,.12)}.join-story span:not(.join-mark),.join-intro>span{display:block;color:#a45b32;font-size:.68rem;font-weight:800;letter-spacing:.12em}.join-story h1{margin:14px 0;font-size:clamp(2.25rem,4vw,3.7rem);font-weight:750;letter-spacing:-.06em;line-height:.96}.join-story p{color:#53617e;line-height:1.6}.join-form-side{display:flex;align-items:center;justify-content:center;padding:48px}.join-form-wrap{width:min(100%,500px)}.join-mobile-brand{display:none}.join-intro h2{margin:8px 0;font-size:2rem;letter-spacing:-.045em}.join-intro p{margin:0;color:var(--color-text-secondary)}.join-form{display:grid;gap:16px;margin-top:30px}.join-form label{display:grid;gap:7px;color:#3e4656;font-size:.78rem;font-weight:700}.join-fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.join-form .btn{margin-top:4px}.join-form-wrap>p{margin-top:24px;color:var(--color-text-secondary);font-size:.82rem;text-align:center}.join-form-wrap a{font-weight:700;text-decoration:none}@media(max-width:800px){.join-experience{display:block}.join-story{display:none}.join-form-side{min-height:100vh;padding:28px 22px}.join-mobile-brand{display:inline-flex;gap:8px;margin-bottom:46px;color:var(--color-text);font-size:.85rem;font-weight:750;text-decoration:none}.join-fields{grid-template-columns:1fr}}
</style>
